@startuml
    actor Client

    control controller
    boundary commandHandler
    boundary Domain
    boundary Repository
    database postgres


    Client -> controller: Request
    controller -> commandHandler: command
    commandHandler -> Domain: create()
    Domain -> Repository: save()
    Repository -> postgres: insert

@enduml